import { buildQuestions, general, no, ok, trf } from './authoring';
import type { AuthoredQuestion } from './authoring';

const seeds: AuthoredQuestion[] = [
  {
    id: 'ris-001',
    category: 'risker',
    subcategory: 'riskbedomning',
    difficulty: 2,
    ruleTested: 'Riskbedömningens grunder',
    prompt: 'Vad kännetecknar en god riskbedömning i trafiken?',
    answers: [
      ok('Du söker aktivt efter det som kan hända, inte bara efter det som händer.'),
      no('Du reagerar snabbt när något oväntat inträffar.'),
      no('Du håller alltid exakt den skyltade hastigheten.', 'skyltad-som-mal'),
      no('Du litar på att andra följer reglerna.', 'blinkers-som-lofte'),
    ],
    short: 'Riskbedömning handlar om att förutse, inte om att reagera snabbt.',
    deep:
      'Snabb reaktion är en sista utväg med små marginaler. Den erfarna föraren skapar i stället marginaler i förväg: sänker farten före en skymd utfart, flyttar sig i sidled från en rad parkerade bilar, och lägger sig så att flyktvägen finns kvar. Frågan att ställa är "vad skulle jag göra om…" innan det händer.',
    memory: 'Kör efter vad som kan hända, inte efter vad som händer.',
    sources: [general('Riskutbildning del 1 och 2')],
  },
  {
    id: 'ris-002',
    category: 'risker',
    subcategory: 'skymd-sikt',
    difficulty: 2,
    ruleTested: 'Hastighet vid skymd sikt',
    prompt: 'Du närmar dig ett backkrön på en smal väg. Vad är rätt?',
    answers: [
      ok('Sänk farten och håll väl till höger — du ska kunna stanna inom den sträcka du ser.'),
      no('Håll farten, krönet är kort.', 'skymd-sikt-fart'),
      no('Kör i mitten av vägen för att ha marginal åt båda hållen.', 'skymd-sikt-fart'),
      no('Tuta innan krönet och håll farten.', 'skymd-sikt-fart'),
    ],
    short: 'Där sikten tar slut måste du kunna stanna. Sänk farten före, inte efter.',
    deep:
      'Grundregeln är att stoppsträckan aldrig får vara längre än den sträcka du överblickar. Vid ett krön ser du kanske trettio meter — då är trettio meter din maximala stoppsträcka, vilket motsvarar en låg hastighet. Ett stillastående fordon, en traktor eller en gående kan stå precis bakom.',
    sources: [trf('3 kap. 14 §')],
    related: ['omk-008'],
  },
  {
    id: 'ris-003',
    category: 'risker',
    subcategory: 'riskbedomning',
    difficulty: 2,
    ruleTested: 'Varningstriangel',
    prompt: 'Din bil har fått motorstopp på en landsväg. Vad gör du först?',
    answers: [
      ok('Sätter på varningsblinkers och varnar övrig trafik med varningstriangel.'),
      no('Öppnar motorhuven och börjar felsöka direkt.'),
      no('Ringer bärgning från förarsätet och väntar i bilen.'),
      no('Går ut på vägen och vinkar med armarna.'),
    ],
    short: 'Varna först — varningsblinkers och triangel — och ställ dig sedan i säkerhet.',
    deep:
      'Triangeln ska placeras så att den syns i god tid, längre bort ju högre hastigheten är och särskilt före krön och kurvor. Bär varselväst om du har en. Rätt ordning är: varna, sätt dig i säkerhet bakom räcket, larma sedan.',
    memory: 'Varna – säkra – larma.',
    sources: [trf('3 kap. 84 §')],
    related: ['par-008'],
  },
  {
    id: 'ris-004',
    category: 'risker',
    subcategory: 'barn-och-oskyddade',
    difficulty: 2,
    ruleTested: 'Barn i trafiken',
    prompt: 'Varför är barn särskilt utsatta som trafikanter?',
    answers: [
      ok('De har svårare att bedöma hastighet och avstånd, och har begränsat synfält i sidled.'),
      no('De hör sämre än vuxna.'),
      no('De rör sig alltid långsammare än vuxna.'),
      no('De känner inte till trafikreglerna.'),
    ],
    short: 'Barn kan reglerna men kan inte bedöma fart och avstånd — och ser mindre åt sidorna.',
    deep:
      'Förmågan att uppskatta hur fort en bil kommer utvecklas sent. Barn har dessutom ett smalare synfält och tolkar situationer bokstavligt: en boll som rullar ut på gatan går före allt annat. Där barn kan förekomma — vid skolor, lekplatser, bussar och parkerade bilar — är låg fart den enda pålitliga marginalen.',
    memory: 'Ser du en boll — bromsa för barnet.',
    sources: [general('Trafikpsykologi: barns utveckling i trafiken')],
  },
  {
    id: 'ris-005',
    category: 'risker',
    subcategory: 'djur-pa-vagen',
    difficulty: 2,
    ruleTested: 'Viltolycka',
    prompt: 'En rådjur springer ut på vägen framför dig och du hinner inte stanna. Vad är rätt?',
    answers: [
      ok('Bromsa hårt rakt fram och släpp bromsen strax före kollisionen om du kan.'),
      no('Väj kraftigt åt vänster in i mötande körfält.', 'djur-vika'),
      no('Väj åt höger ner i diket.', 'djur-vika'),
      no('Öka farten för att passera före djuret.', 'djur-vika'),
    ],
    short: 'Bromsa rakt fram. En undanmanöver i hög fart är oftast farligare än kollisionen.',
    deep:
      'Att väja mot mötande trafik eller ner i ett dike ger typiskt allvarligare skador än en påkörning av ett mindre djur. Att släppa bromsen precis före krocken höjer bilens front något, vilket kan minska risken att djuret kastas upp mot vindrutan. Vid större vilt som älg är kollisionen livsfarlig — där är kraftig inbromsning och hastighetsanpassning i riskområden det som gäller.',
    sources: [general('Trafiksäkerhet: viltolyckor')],
    related: ['ris-006'],
  },
  {
    id: 'ris-006',
    category: 'risker',
    subcategory: 'djur-pa-vagen',
    difficulty: 1,
    ruleTested: 'Anmälningsplikt vid viltolycka',
    prompt: 'Du kör på ett rådjur och det springer in i skogen. Vad gäller?',
    answers: [
      ok('Du måste märka ut olycksplatsen och anmäla händelsen till polisen.'),
      no('Ingen anmälan behövs om djuret sprang vidare.'),
      no('Anmälan behövs bara om bilen fick skador.'),
      no('Det räcker att kontakta ditt försäkringsbolag.'),
    ],
    short: 'Viltolycka ska alltid anmälas till polisen — även om djuret försvann.',
    deep:
      'Anmälningsplikten gäller bland annat älg, rådjur, hjort, vildsvin, björn, varg, lo, järv, örn, mufflonfår och utter. Skälet är djurskydd: ett skadat djur ska kunna spåras och avlivas. Märk ut platsen där djuret försvann så att eftersöksjägaren hittar rätt.',
    sources: [general('Jaktförordningen, anmälningsplikt vid sammanstötning med vilt')],
    related: ['ris-005'],
  },
  {
    id: 'ris-007',
    category: 'risker',
    subcategory: 'skymd-sikt',
    difficulty: 3,
    ruleTested: 'Parkerade bilar som risk',
    prompt: 'Du kör på en bostadsgata med parkerade bilar längs höger sida. Vilken risk är störst?',
    answers: [
      ok('Att någon kliver ut mellan bilarna eller att en dörr öppnas.'),
      no('Att en bil startar och kör om dig.'),
      no('Att vägbanan är smalare än normalt.'),
      no('Att du får svårt att hitta en parkeringsplats.'),
    ],
    short: 'Parkerade bilar döljer människor. Flytta dig i sidled och sänk farten.',
    deep:
      'Två åtgärder fungerar: öka sidoavståndet till de parkerade bilarna så att du får både sikt och tid, och sänk farten så att stoppsträckan ryms inom det du ser. Titta efter ledtrådar — fötter under bilarna, bakljus som tänds, huvuden i bakrutorna.',
    sources: [general('Riskutbildning: stadsmiljö')],
  },
  {
    id: 'ris-008',
    category: 'risker',
    subcategory: 'riskbedomning',
    difficulty: 3,
    ruleTested: 'Krockvåld och hastighet',
    prompt: 'Varför är skillnaden mellan 30 och 50 km/h så stor vid en påkörning av en gående?',
    answers: [
      ok('Krockvåldet växer med hastigheten i kvadrat, så risken att dödas ökar dramatiskt.'),
      no('Bilens bromsar fungerar sämre över 30 km/h.'),
      no('Gående hinner inte höra bilen vid högre hastighet.'),
      no('Skillnaden är i praktiken liten.'),
    ],
    short: 'Rörelseenergin fyrdubblas ungefär när farten går från 30 till 50 km/h.',
    deep:
      'Rörelseenergin är proportionell mot hastigheten i kvadrat. 50 dividerat med 30 är 1,67, och kvadrerat blir det knappt 2,8 — nästan tre gånger så mycket energi som ska tas upp av en människokropp. Det är därför 30 km/h används där gående och fordon möts, och varför "bara lite för fort" inte är ett litet fel.',
    type: 'calculation',
    sources: [general('Trafiksäkerhet: krockvåld och hastighet')],
    related: ['has-006'],
  },
  {
    id: 'ris-009',
    category: 'risker',
    subcategory: 'barn-och-oskyddade',
    difficulty: 2,
    ruleTested: 'Passage av buss',
    prompt: 'En buss står vid en hållplats och släpper av passagerare. Vad bör du göra?',
    answers: [
      ok('Sänka farten kraftigt och vara beredd på att någon springer ut framför bussen.'),
      no('Köra om bussen i oförändrad hastighet på vänster sida.'),
      no('Tuta så att de som stiger av uppmärksammar dig.'),
      no('Köra nära bussen så att du snabbt passerar.'),
    ],
    short: 'Bussen skymmer sikten. Räkna med att någon korsar vägen framför den.',
    deep:
      'Det klassiska förloppet är att en passagerare, ofta ett barn, går framför bussen för att korsa gatan och varken ser eller syns. Låg fart och stort sidoavstånd ger dig den tid du behöver. Inom tätbebyggt område där gränsen är högst 50 km/h ska du dessutom släppa ut bussen när den blinkar.',
    sources: [trf('3 kap. 12 §')],
    related: ['tra-009'],
  },
  {
    id: 'ris-010',
    category: 'risker',
    subcategory: 'riskbedomning',
    difficulty: 3,
    ruleTested: 'Flyktväg',
    prompt: 'Vad menas med att alltid ha en flyktväg när du kör?',
    answers: [
      ok('Att du placerar dig och håller avstånd så att du har någonstans att ta vägen om något händer.'),
      no('Att du alltid vet var närmaste avfart finns.'),
      no('Att du kör i det körfält som har minst trafik.'),
      no('Att du håller så hög fart att du kan gasa dig ur en situation.'),
    ],
    short: 'En flyktväg är ett utrymme du medvetet håller öppet — oftast framåt och åt sidan.',
    deep:
      'I praktiken betyder det att du undviker att ligga i någons döda vinkel, att du inte hamnar inklämd mellan två tunga fordon, och att du håller så långt avstånd framåt att du kan bromsa i stället för att väja. Utrymme är den enda resurs som faktiskt hjälper när något oväntat händer.',
    sources: [general('Körstrategi: utrymme och flyktvägar')],
  },
];

export const riskerQuestions = buildQuestions(seeds);
