import { buildQuestions, no, ok, sign, trf, vmf } from './authoring';
import type { AuthoredQuestion } from './authoring';

const seeds: AuthoredQuestion[] = [
  {
    id: 'vag-001',
    category: 'vagmarken',
    subcategory: 'varningsmarken',
    difficulty: 1,
    ruleTested: 'Varningsmärkens form och färg',
    prompt: 'Hur känner du igen ett varningsmärke i Sverige?',
    answers: [
      ok('Gul triangel med röd ram, ställd på spetsen uppåt.'),
      no('Blå cirkel med vit symbol.'),
      no('Blå fyrkant med vit symbol.'),
      no('Gul romb med vit kant.'),
    ],
    short: 'Varningsmärken är gula trianglar med röd ram.',
    deep:
      'Formen och färgen bär informationen även när du inte hinner läsa symbolen. Triangel varnar, rund skylt med röd ram förbjuder, blå rund skylt påbjuder och blå fyrkant ger anvisning. Att läsa formen först och symbolen sedan gör att du hinner reagera tidigare.',
    memory: 'Triangel varnar, cirkel bestämmer, fyrkant informerar.',
    sources: [vmf('2 kap.')],
    type: 'road-sign',
    image: sign('varning-korsning', 'Varningsmärke: gul triangel med röd ram och ett svart kors.'),
    accessibilityText: 'En gul triangel med röd ram och ett svart kryss som symbol.',
  },
  {
    id: 'vag-002',
    category: 'vagmarken',
    subcategory: 'varningsmarken',
    difficulty: 2,
    ruleTested: 'Varningsmärkets innebörd',
    prompt: 'Vad innebär ett varningsmärke rent juridiskt?',
    answers: [
      ok('Det upplyser om en fara — du ska anpassa körningen, men märket ändrar inga väjningsregler.'),
      no('Det ger dig företräde eftersom du är förvarnad.'),
      no('Det innebär alltid att hastighetsgränsen sänks.', 'skyltad-som-mal'),
      no('Det innebär stopplikt vid faran.', 'stopp-utan-stopp'),
    ],
    short: 'Varningsmärken varnar. De ger varken företräde eller ny hastighetsgräns.',
    deep:
      'Ett varningsmärke för vägkorsning betyder inte att du har företräde i korsningen — där gäller fortfarande högerregeln om inget annat är skyltat. Märket säger bara: något kommer, var beredd.',
    sources: [vmf('2 kap.')],
  },
  {
    id: 'vag-003',
    category: 'vagmarken',
    subcategory: 'forbudsmarken',
    difficulty: 1,
    ruleTested: 'Förbudsmärkens giltighet',
    prompt: 'Hur länge gäller normalt ett förbudsmärke som satts upp vid en väg?',
    answers: [
      ok('Fram till nästa korsning, om inget annat anges med tilläggstavla.'),
      no('Exakt 500 meter från märket.'),
      no('Tills du ser samma märke igen.'),
      no('Under hela vägens sträckning fram till tätortsgränsen.'),
    ],
    short: 'Förbudsmärken gäller normalt fram till nästa korsning.',
    deep:
      'Undantag anges med tilläggstavla, till exempel en sträckangivelse eller ett slutmärke. Regeln är praktisk: efter en korsning kan förutsättningarna vara andra, och nya trafikanter som svänger in måste kunna se skyltningen som gäller dem.',
    sources: [vmf('2 kap.')],
  },
  {
    id: 'vag-004',
    category: 'vagmarken',
    subcategory: 'forbudsmarken',
    difficulty: 2,
    ruleTested: 'Förbud mot infart',
    prompt: 'Vad betyder ett runt rött märke med ett vitt vågrätt streck i mitten?',
    answers: [
      ok('Förbud mot infart med fordon — vägen är enkelriktad åt andra hållet.'),
      no('Förbud mot att stanna och parkera.', 'stanna-vs-parkera'),
      no('Stopplikt.', 'stopp-utan-stopp'),
      no('Förbud mot omkörning.'),
    ],
    short: 'Rött märke med vitt streck betyder förbud mot infart — oftast en enkelriktad gata.',
    deep:
      'Märket sitter i den ände där du inte får köra in. Ser du det när du redan är på gatan har du kommit in från fel håll. Förväxla det inte med förbud mot trafik med fordon, som är ett tomt rött märke med vit ram.',
    sources: [vmf('C1')],
    type: 'road-sign',
    image: sign('forbud-infart', 'Vägmärke: rund röd skylt med ett vitt vågrätt streck.'),
    accessibilityText: 'En rund röd skylt med ett brett vitt streck tvärs över mitten.',
  },
  {
    id: 'vag-005',
    category: 'vagmarken',
    subcategory: 'pabudsmarken',
    difficulty: 1,
    ruleTested: 'Påbudsmärken',
    prompt: 'Vad betyder ett blått runt märke med en vit pil rakt fram?',
    answers: [
      ok('Påbjuden körriktning — du måste köra rakt fram.'),
      no('Rekommenderad körriktning, du får välja själv.'),
      no('Enkelriktad väg i pilens riktning.'),
      no('Motorväg börjar.'),
    ],
    short: 'Blå rund skylt med vit pil är ett påbud: du ska köra i pilens riktning.',
    deep:
      'Blå rund skylt = du måste. Blå fyrkantig skylt = information om vad som gäller på sträckan. Det är en användbar genväg när du bara hinner uppfatta formen.',
    sources: [vmf('D1')],
    type: 'road-sign',
    image: sign('pabud-rakt', 'Vägmärke: blå rund skylt med en vit pil uppåt.'),
    accessibilityText: 'En blå rund skylt med en vit pil som pekar rakt uppåt.',
  },
  {
    id: 'vag-006',
    category: 'vagmarken',
    subcategory: 'anvisningsmarken',
    difficulty: 2,
    ruleTested: 'Gågata',
    prompt: 'Vad gäller för motorfordon på en gågata?',
    answers: [
      ok('Körning är tillåten bara i vissa undantagsfall, i gångfart, och du har väjningsplikt mot gående.'),
      no('Samma regler som på en vanlig gata, men med 30 km/h.', 'bashastighet-tatort'),
      no('Gående har väjningsplikt mot fordon som kör där lagligt.'),
      no('All motortrafik är alltid förbjuden utan undantag.'),
    ],
    short: 'På gågata gäller gångfart, väjningsplikt mot gående och parkeringsförbud.',
    deep:
      'Undantagen gäller till exempel varuleveranser och färdtjänst. Kör du ut från en gågata gäller dessutom utfartsregeln — du har väjningsplikt mot all trafik på vägen du kommer ut på.',
    sources: [trf('8 kap. 1 §')],
    related: ['kor-003'],
  },
  {
    id: 'vag-007',
    category: 'vagmarken',
    subcategory: 'anvisningsmarken',
    difficulty: 2,
    ruleTested: 'Gångfartsområde',
    prompt: 'Vilken hastighet gäller i ett gångfartsområde?',
    answers: [
      ok('Gångfart — omkring 7 km/h, alltså inte fortare än en person går.'),
      no('30 km/h.', 'bashastighet-tatort'),
      no('20 km/h.', 'bashastighet-tatort'),
      no('50 km/h som i övrig tätort.', 'bashastighet-tatort'),
    ],
    short: 'I gångfartsområde kör du i gångfart och har väjningsplikt mot gående.',
    deep:
      'Ingen exakt siffra står i förordningen, men gångfart brukar anges till ungefär 7 km/h. Parkering är bara tillåten på särskilt anordnade platser. Området är utformat så att gående och fordon delar ytan — därför är väjningsplikten mot gående central.',
    sources: [trf('8 kap. 1 §')],
  },
  {
    id: 'vag-008',
    category: 'vagmarken',
    subcategory: 'vagmarkeringar',
    difficulty: 2,
    ruleTested: 'Heldragen linje',
    prompt: 'Vad gäller vid en heldragen mittlinje?',
    answers: [
      ok('Du får inte köra över eller på linjen, förutom när det behövs för att undvika en fara.'),
      no('Du får korsa den vid omkörning om vägen är fri.', 'omkorning-hoger'),
      no('Den är bara en rekommendation.'),
      no('Den betyder alltid omkörningsförbud för alla fordon på hela sträckan.'),
    ],
    short: 'Heldragen linje får inte korsas — undantag bara vid nödvändighet, till exempel ett hinder.',
    deep:
      'Om en heldragen och en streckad linje ligger bredvid varandra gäller den som är närmast dig. Ligger den streckade på din sida får du korsa. Att korsa för att passera ett hinder på vägen är tillåtet, men bara om det kan ske utan fara.',
    sources: [trf('3 kap. 11 §')],
  },
  {
    id: 'vag-009',
    category: 'vagmarken',
    subcategory: 'vagmarkeringar',
    difficulty: 2,
    ruleTested: 'Spärrområde',
    prompt: 'Vad betyder ett vitt streckat område på vägbanan mellan två körfält, ett spärrområde?',
    answers: [
      ok('Ytan ska inte användas för körning — den skiljer trafikströmmar åt.'),
      no('Det är en extra fil som får användas vid köbildning.'),
      no('Det är en tillfällig parkeringsyta.'),
      no('Det markerar en cykelpassage.'),
    ],
    short: 'Ett spärrområde är inte ett körfält. Du ska inte köra eller stanna där.',
    deep:
      'Spärrområden används där körfält delas eller går ihop, ofta före avfarter och vid vänstersvängfält. Att köra på ytan tar bort just den buffert som ska skydda mot krockar mellan trafikströmmar.',
    sources: [trf('3 kap. 11 §')],
  },
  {
    id: 'vag-010',
    category: 'vagmarken',
    subcategory: 'forbudsmarken',
    difficulty: 2,
    ruleTested: 'Hastighetsmärke',
    prompt: 'Du passerar en rund skylt med gul botten, röd ram och siffran 70. Vad betyder det?',
    answers: [
      ok('Högsta tillåtna hastighet är 70 km/h.'),
      no('Rekommenderad hastighet är 70 km/h.', 'skyltad-som-mal'),
      no('Lägsta tillåtna hastighet är 70 km/h.'),
      no('Hastigheten 70 km/h gäller endast för tunga fordon.'),
    ],
    short: 'Rund skylt med röd ram anger högsta tillåtna hastighet — ett tak, inte ett mål.',
    deep:
      'En blå rund skylt med en siffra betyder däremot påbjuden lägsta hastighet, och en fyrkantig skylt med siffra kan ange rekommenderad högsta hastighet vid till exempel en kurva. Det är bara den runda skylten med röd ram som är en juridiskt bindande gräns.',
    sources: [vmf('C31')],
    type: 'road-sign',
    image: sign('hastighet-70', 'Vägmärke: rund skylt med gul botten, röd ram och siffran 70.'),
    accessibilityText: 'En rund skylt med gul botten, bred röd ram och den svarta siffran 70.',
  },
  {
    id: 'vag-011',
    category: 'vagmarken',
    subcategory: 'anvisningsmarken',
    difficulty: 1,
    ruleTested: 'Väjningsplikt',
    prompt: 'Vilken form och färg har märket för väjningsplikt?',
    answers: [
      ok('En triangel med spetsen nedåt, gul yta och röd ram.'),
      no('En röd åttakant med texten VÄJ.'),
      no('En blå cirkel med vit triangel.'),
      no('En gul romb med vit kant.'),
    ],
    short: 'Väjningsplikt är den enda triangeln som står på spetsen.',
    deep:
      'Formen är unik just för att den ska kunna kännas igen även bakifrån eller när skylten är smutsig. Väjningsplikt betyder att du ska sänka farten och lämna företräde — men du behöver inte stanna om vägen är fri.',
    sources: [vmf('B1')],
    type: 'road-sign',
    image: sign('vajningsplikt', 'Vägmärke: gul triangel med röd ram och spetsen nedåt.'),
    accessibilityText: 'En triangel med spetsen nedåt, gul yta och bred röd ram.',
  },
  {
    id: 'vag-012',
    category: 'vagmarken',
    subcategory: 'varningsmarken',
    difficulty: 3,
    ruleTested: 'Avstånd till faran',
    prompt: 'På hur långt avstånd före faran sitter ett varningsmärke normalt utanför tätort?',
    answers: [
      ok('Avståndet anpassas efter hastigheten — ju högre hastighet, desto längre före.'),
      no('Alltid exakt 150 meter.'),
      no('Alltid exakt 50 meter.'),
      no('Direkt vid faran, så att du ser båda samtidigt.'),
    ],
    short: 'Placeringen följer hastigheten så att du hinner reagera och anpassa farten.',
    deep:
      'Ett varningsmärke ska ge tid, inte bara information. Vid högre hastighet sitter det längre före. Behöver avståndet förtydligas används en tilläggstavla som anger sträckan i meter.',
    sources: [vmf('2 kap.')],
  },
];

export const vagmarkenQuestions = buildQuestions(seeds);
