/**
 * GENERATED FILE — do not edit by hand.
 *
 * Run `npm run generate:index` after changing the question bank.
 * A test asserts this file matches the bank, so a stale index fails the suite.
 *
 * Why it exists: the full bank is ~470 kB of JSON, dominated by answers,
 * explanations and source references. Hydration, the mastery model and the
 * landing page need none of that — only which questions exist and where they
 * sit in the taxonomy. Keeping that here lets the bank itself load lazily.
 */

import { LEARNER_VISIBLE_STATUSES } from '@/domain/content/types';
import type { CategoryId, Difficulty, QuestionStatus } from '@/domain/content/types';

export interface QuestionIndexEntry {
  id: string;
  category: CategoryId;
  subcategory: string;
  difficulty: Difficulty;
  status: QuestionStatus;
  ruleTested: string;
}

/** Compact rows: [id, category, subcategory, difficulty, status, ruleTested]. */
const ROWS: ReadonlyArray<readonly [string, string, string, number, string, string]> = [
  ['tra-001', 'trafikregler', 'grundregler', 1, 'reviewed', "Allmän aktsamhetsplikt"],
  ['tra-002', 'trafikregler', 'trafiksignaler', 1, 'reviewed', "Signalbilder"],
  ['tra-003', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Obevakat övergångsställe"],
  ['tra-004', 'trafikregler', 'oskyddade-trafikanter', 3, 'reviewed', "Cykelöverfart och cykelpassage"],
  ['tra-005', 'trafikregler', 'vagens-anvandning', 1, 'reviewed', "Grundregel för placering"],
  ['tra-006', 'trafikregler', 'korfalt-och-sving', 2, 'reviewed', "Placering före sväng"],
  ['tra-007', 'trafikregler', 'trafiksignaler', 2, 'reviewed', "Utryckningsfordon"],
  ['tra-008', 'trafikregler', 'grundregler', 2, 'reviewed', "Tecken"],
  ['tra-009', 'trafikregler', 'vagens-anvandning', 2, 'reviewed', "Busshållplats i tätort"],
  ['tra-010', 'trafikregler', 'korfalt-och-sving', 3, 'reviewed', "Körfältsbyte"],
  ['bel-001', 'fordonet', 'belysning-fordon', 1, 'reviewed', "Varselljus"],
  ['bel-002', 'fordonet', 'belysning-fordon', 2, 'reviewed', "Kombination av ljus"],
  ['bel-003', 'fordonet', 'belysning-fordon', 2, 'reviewed', "Främre dimljus"],
  ['bel-004', 'fordonet', 'belysning-fordon', 2, 'reviewed', "Dimbakljus"],
  ['bel-005', 'halka', 'dimma', 2, 'reviewed', "Helljus i dimma"],
  ['bel-006', 'halka', 'dimma', 3, 'reviewed', "Hastighet vid kraftigt nedsatt sikt"],
  ['bel-007', 'morker', 'mote-i-morker', 2, 'reviewed', "Avbländning vid möte"],
  ['bel-008', 'morker', 'mote-i-morker', 3, 'reviewed', "Avbländning vid omkörning"],
  ['bel-009', 'morker', 'mote-i-morker', 3, 'reviewed', "Möte med lastbil i backkrön"],
  ['bel-010', 'morker', 'mote-i-morker', 2, 'reviewed', "Helljus vid korsning i mörker"],
  ['bel-011', 'morker', 'mote-i-morker', 1, 'reviewed', "Blickpunkt vid bländning"],
  ['vaj-001', 'korsningar', 'polisens-tecken', 2, 'reviewed', "Rangordning: signal före vägmärke"],
  ['vaj-002', 'korsningar', 'polisens-tecken', 2, 'reviewed', "Rangordning när signalen är ur funktion"],
  ['vaj-003', 'korsningar', 'huvudled', 3, 'reviewed', "Var huvudledsmärket sitter"],
  ['vaj-004', 'korsningar', 'huvudled', 2, 'reviewed', "När huvudleden upphör"],
  ['vaj-005', 'korsningar', 'utfartsregeln', 3, 'reviewed', "När utfartsregeln inte gäller"],
  ['vaj-006', 'korsningar', 'utfartsregeln', 2, 'reviewed', "Platser som utlöser utfartsregeln"],
  ['vaj-007', 'korsningar', 'trafiksignal-korsning', 3, 'reviewed', "Släckt pil vid rund grön signal"],
  ['vaj-008', 'korsningar', 'trafiksignal-korsning', 2, 'reviewed', "Grön pil"],
  ['vaj-009', 'motorvag', 'motortrafikled', 2, 'reviewed', "Regler på motortrafikled"],
  ['vaj-010', 'motorvag', 'motortrafikled', 3, 'reviewed', "Mötesfri väg som inte är motortrafikled"],
  ['vaj-011', 'omkorning', 'mote', 3, 'reviewed', "Bedöma mötande fordon"],
  ['vaj-012', 'omkorning', 'mote', 2, 'reviewed', "Skyldighet vid otillåten omkörning"],
  ['vaj-013', 'halka', 'vattenplaning', 3, 'reviewed', "Däckbredd och vattenplaning"],
  ['vaj-014', 'halka', 'vattenplaning', 2, 'reviewed', "Ratten vid vattenplaning"],
  ['vaj-015', 'halka', 'vattenplaning', 2, 'reviewed', "Moddplaning"],
  ['vag-001', 'vagmarken', 'varningsmarken', 1, 'reviewed', "Varningsmärkens form och färg"],
  ['vag-002', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Varningsmärkets innebörd"],
  ['vag-003', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Förbudsmärkens giltighet"],
  ['vag-004', 'vagmarken', 'forbudsmarken', 2, 'reviewed', "Förbud mot infart"],
  ['vag-005', 'vagmarken', 'pabudsmarken', 1, 'reviewed', "Påbudsmärken"],
  ['vag-006', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Gågata"],
  ['vag-007', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Gångfartsområde"],
  ['vag-008', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Heldragen linje"],
  ['vag-009', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Spärrområde"],
  ['vag-010', 'vagmarken', 'forbudsmarken', 2, 'reviewed', "Hastighetsmärke"],
  ['vag-011', 'vagmarken', 'anvisningsmarken', 1, 'reviewed', "Väjningsplikt"],
  ['vag-012', 'vagmarken', 'varningsmarken', 3, 'reviewed', "Avstånd till faran"],
  ['has-001', 'hastighet', 'hastighetsgranser', 1, 'reviewed', "Bashastighet"],
  ['has-002', 'hastighet', 'hastighetsgranser', 1, 'reviewed', "Bashastighet utanför tätort"],
  ['has-003', 'hastighet', 'anpassad-hastighet', 2, 'reviewed', "Anpassad hastighet"],
  ['has-004', 'hastighet', 'avstand', 2, 'reviewed', "Avstånd till framförvarande"],
  ['has-005', 'hastighet', 'anpassad-hastighet', 3, 'reviewed', "Sträcka per sekund"],
  ['has-006', 'hastighet', 'anpassad-hastighet', 3, 'reviewed', "Bromssträckans förhållande till hastigheten"],
  ['has-007', 'hastighet', 'placering', 2, 'reviewed', "Placering på flerfilig väg"],
  ['has-008', 'hastighet', 'placering', 2, 'reviewed', "Sidoavstånd till cyklist"],
  ['has-009', 'hastighet', 'hastighetsgranser', 2, 'reviewed', "Hastighet med släp"],
  ['has-010', 'hastighet', 'avstand', 3, 'reviewed', "Avstånd bakom tungt fordon"],
  ['kor-001', 'korsningar', 'hogerregeln', 1, 'reviewed', "Högerregeln"],
  ['kor-002', 'korsningar', 'utfartsregeln', 2, 'reviewed', "Utfartsregeln"],
  ['kor-003', 'korsningar', 'utfartsregeln', 2, 'reviewed', "Utfartsregeln"],
  ['kor-004', 'korsningar', 'stopplikt', 1, 'reviewed', "Stopplikt"],
  ['kor-005', 'korsningar', 'cirkulationsplats', 1, 'reviewed', "Cirkulationsplats"],
  ['kor-006', 'korsningar', 'cirkulationsplats', 2, 'reviewed', "Tecken i cirkulationsplats"],
  ['kor-007', 'korsningar', 'huvudled', 2, 'reviewed', "Huvudled"],
  ['kor-008', 'korsningar', 'huvudled', 1, 'reviewed', "Huvudled"],
  ['kor-009', 'korsningar', 'vajningsplikt', 2, 'reviewed', "Väjningsplikt i praktiken"],
  ['kor-010', 'korsningar', 'vajningsplikt', 3, 'reviewed', "Blinkers som avsikt"],
  ['kor-011', 'korsningar', 'trafiksignal-korsning', 2, 'reviewed', "Gult ljus"],
  ['kor-012', 'korsningar', 'trafiksignal-korsning', 2, 'reviewed', "Grön signal och väjningsplikt"],
  ['kor-013', 'korsningar', 'polisens-tecken', 2, 'reviewed', "Rangordning mellan tecken"],
  ['kor-014', 'korsningar', 'hogerregeln', 3, 'reviewed', "Högerregeln i praktiken"],
  ['kor-015', 'korsningar', 'vajningsplikt', 3, 'reviewed', "Blockerad korsning"],
  ['kor-016', 'korsningar', 'stopplikt', 2, 'reviewed', "Stopplinje"],
  ['cir-001', 'korsningar', 'cirkulationsplats', 1, 'reviewed', "Väjningsplikt vid infart i cirkulationsplats"],
  ['cir-002', 'korsningar', 'cirkulationsplats', 1, 'reviewed', "Körriktning i cirkulationsplats"],
  ['cir-003', 'korsningar', 'cirkulation-korfalt', 2, 'reviewed', "Tecken vid utfart ur cirkulationsplats"],
  ['cir-004', 'korsningar', 'cirkulation-korfalt', 2, 'reviewed', "Tecken vid infart i cirkulationsplats"],
  ['cir-005', 'korsningar', 'cirkulation-korfalt', 3, 'reviewed', "Vänsterblinkning i cirkulationsplats"],
  ['cir-006', 'korsningar', 'cirkulation-korfalt', 2, 'reviewed', "Körfältsval i cirkulationsplats"],
  ['cir-007', 'korsningar', 'cirkulation-korfalt', 3, 'reviewed', "Körfältsbyte inne i cirkulationsplats"],
  ['cir-008', 'korsningar', 'cirkulationsplats', 3, 'reviewed', "Cirkelformad korsning som inte är cirkulationsplats"],
  ['cir-009', 'korsningar', 'cirkulationsplats', 2, 'reviewed', "Oskyddade trafikanter vid cirkulationsplats"],
  ['cir-010', 'korsningar', 'cirkulationsplats', 1, 'reviewed', "Varför cirkulationsplatser byggs"],
  ['cir-011', 'korsningar', 'cirkulation-korfalt', 2, 'reviewed', "Att underlätta andras körfältsbyten"],
  ['cir-012', 'korsningar', 'cirkulationsplats', 3, 'reviewed', "Huvudled och cirkulationsplats"],
  ['jvg-001', 'jarnvag', 'plankorsning-marken', 1, 'reviewed', "Avstånd till plankorsning (A38)"],
  ['jvg-002', 'jarnvag', 'plankorsning-marken', 2, 'reviewed', "Ljussignal vid plankorsning"],
  ['jvg-003', 'jarnvag', 'plankorsning-marken', 1, 'reviewed', "Helbom och halvbom"],
  ['jvg-004', 'jarnvag', 'plankorsning-marken', 2, 'reviewed', "Plankorsning utan bommar"],
  ['jvg-005', 'jarnvag', 'plankorsning-korning', 2, 'reviewed', "Anpassning efter sikt vid plankorsning"],
  ['jvg-006', 'jarnvag', 'plankorsning-korning', 2, 'reviewed', "Växelval vid plankorsning"],
  ['jvg-007', 'jarnvag', 'plankorsning-korning', 2, 'reviewed', "Köbildning vid plankorsning"],
  ['jvg-008', 'jarnvag', 'plankorsning-korning', 3, 'reviewed', "Motorstopp på spåret"],
  ['jvg-009', 'jarnvag', 'plankorsning-korning', 1, 'reviewed', "Motorstopp på spåret"],
  ['jvg-010', 'jarnvag', 'plankorsning-korning', 3, 'reviewed', "Bedömning av tågets hastighet"],
  ['jvg-011', 'jarnvag', 'plankorsning-korning', 2, 'reviewed', "Efter plankorsningen"],
  ['jvg-012', 'jarnvag', 'plankorsning-korning', 3, 'reviewed', "Långsamma fordon vid plankorsning"],
  ['jvg-013', 'jarnvag', 'plankorsning-omkorning', 2, 'reviewed', "Omkörningsförbud vid plankorsning"],
  ['jvg-014', 'jarnvag', 'plankorsning-omkorning', 3, 'reviewed', "Vilken signal som upphäver omkörningsförbudet"],
  ['jvg-015', 'jarnvag', 'plankorsning-omkorning', 2, 'reviewed', "Omkörning vid plankorsning med bommar"],
  ['jvg-016', 'jarnvag', 'plankorsning-marken', 2, 'reviewed', "Varning för järnvägskorsning"],
  ['pas-001', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Att visa sin avsikt att väja"],
  ['pas-002', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Bevakat övergångsställe"],
  ['pas-003', 'trafikregler', 'oskyddade-trafikanter', 3, 'reviewed', "Bevakat eller obevakat övergångsställe"],
  ['pas-004', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Vem som räknas som gående"],
  ['pas-005', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Att vinka fram gående"],
  ['pas-006', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Att korsa en gångbana"],
  ['pas-007', 'trafikregler', 'oskyddade-trafikanter', 3, 'reviewed', "Gångbana som inte korsar vägen"],
  ['pas-008', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Obevakad cykelpassage"],
  ['pas-009', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Cykelpassage i samband med sväng"],
  ['pas-010', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Cyklistens skyldighet vid cykelpassage"],
  ['pas-011', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Cykelöverfart"],
  ['pas-012', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Vilka väjningsplikten vid cykelöverfart omfattar"],
  ['pas-013', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Utformning av cykelöverfart"],
  ['pas-014', 'trafikregler', 'cykelpassage-overfart', 1, 'reviewed', "Att skilja passage från överfart"],
  ['pas-015', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Att korsa en cykelbana"],
  ['pas-016', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Bevakad cykelpassage"],
  ['par-001', 'parkering', 'parkeringsforbud', 1, 'reviewed', "Skillnad stannande och parkering"],
  ['par-002', 'parkering', 'stannande-forbud', 2, 'reviewed', "Tiometersregeln"],
  ['par-003', 'parkering', 'stannande-forbud', 2, 'reviewed', "Stannande i korsning"],
  ['par-004', 'parkering', 'parkeringsforbud', 2, 'reviewed', "Parkering på huvudled"],
  ['par-005', 'parkering', 'parkeringsregler', 2, 'reviewed', "Parkering i färdriktningen"],
  ['par-006', 'parkering', 'stannande-forbud', 1, 'reviewed', "Förbud att stanna och parkera"],
  ['par-007', 'parkering', 'parkeringsregler', 2, 'reviewed', "Parkering och utfarter"],
  ['par-008', 'parkering', 'parkeringsforbud', 3, 'reviewed', "Parkering på backkrön och i kurva"],
  ['par-009', 'parkering', 'parkeringsregler', 2, 'reviewed', "Parkeringsskyltens tilläggstavlor"],
  ['par-010', 'parkering', 'stannande-forbud', 3, 'reviewed', "Stannande i cykelfält"],
  ['mot-001', 'motorvag', 'pafart-avfart', 2, 'reviewed', "Påfart till motorväg"],
  ['mot-002', 'motorvag', 'motorvag-regler', 1, 'reviewed', "Fordon som inte får köra på motorväg"],
  ['mot-003', 'motorvag', 'motorvag-regler', 2, 'reviewed', "Vägren på motorväg"],
  ['mot-004', 'motorvag', 'motorvag-regler', 1, 'reviewed', "Förbjudna manövrar"],
  ['mot-005', 'motorvag', 'pafart-avfart', 2, 'reviewed', "Avfart från motorväg"],
  ['mot-006', 'motorvag', 'motorvag-regler', 3, 'reviewed', "Hastighetsanpassning efter motorväg"],
  ['mot-007', 'motorvag', 'motortrafikled', 2, 'reviewed', "Motortrafikled"],
  ['mot-008', 'motorvag', 'landsvag', 2, 'reviewed', "Mötesfri landsväg"],
  ['mot-009', 'motorvag', 'motorvag-regler', 2, 'reviewed', "Körfältsval på motorväg"],
  ['mot-010', 'motorvag', 'landsvag', 3, 'reviewed', "Landsvägens risker"],
  ['omk-001', 'omkorning', 'omkorningsregler', 1, 'reviewed', "Omkörningens huvudregel"],
  ['omk-002', 'omkorning', 'omkorningsregler', 2, 'reviewed', "Omkörning till höger"],
  ['omk-003', 'omkorning', 'omkorningsforbud', 2, 'reviewed', "Omkörning vid övergångsställe"],
  ['omk-004', 'omkorning', 'omkorningsforbud', 2, 'reviewed', "Omkörning före korsning"],
  ['omk-005', 'omkorning', 'omkorningsregler', 3, 'reviewed', "Omkörningens tid och sträcka"],
  ['omk-006', 'omkorning', 'mote', 2, 'reviewed', "Möte på smal väg"],
  ['omk-007', 'omkorning', 'omkorningsregler', 2, 'reviewed', "Att bli omkörd"],
  ['omk-008', 'omkorning', 'omkorningsforbud', 3, 'reviewed', "Sikt vid omkörning"],
  ['ris-001', 'risker', 'riskbedomning', 2, 'reviewed', "Riskbedömningens grunder"],
  ['ris-002', 'risker', 'skymd-sikt', 2, 'reviewed', "Hastighet vid skymd sikt"],
  ['ris-003', 'risker', 'riskbedomning', 2, 'reviewed', "Varningstriangel"],
  ['ris-004', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Barn i trafiken"],
  ['ris-005', 'risker', 'djur-pa-vagen', 2, 'reviewed', "Viltolycka"],
  ['ris-006', 'risker', 'djur-pa-vagen', 1, 'reviewed', "Anmälningsplikt vid viltolycka"],
  ['ris-007', 'risker', 'skymd-sikt', 3, 'reviewed', "Parkerade bilar som risk"],
  ['ris-008', 'risker', 'riskbedomning', 3, 'reviewed', "Krockvåld och hastighet"],
  ['ris-009', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Passage av buss"],
  ['ris-010', 'risker', 'riskbedomning', 3, 'reviewed', "Flyktväg"],
  ['alk-001', 'alkohol', 'alkohol-gransvarden', 1, 'reviewed', "Promillegräns"],
  ['alk-002', 'alkohol', 'alkohol-gransvarden', 2, 'reviewed', "Grovt rattfylleri"],
  ['alk-003', 'alkohol', 'alkohol-effekter', 2, 'reviewed', "Alkoholens nedbrytning"],
  ['alk-004', 'alkohol', 'alkohol-effekter', 2, 'reviewed', "Dagen efter"],
  ['alk-005', 'alkohol', 'alkohol-effekter', 2, 'reviewed', "Alkoholens effekt på körförmågan"],
  ['alk-006', 'alkohol', 'droger-lakemedel', 2, 'reviewed', "Läkemedel och körning"],
  ['alk-007', 'alkohol', 'droger-lakemedel', 1, 'reviewed', "Nolltolerans mot narkotika"],
  ['alk-008', 'alkohol', 'alkohol-gransvarden', 3, 'reviewed', "Ansvar för annan förare"],
  ['tro-001', 'trotthet', 'trotthet', 1, 'reviewed', "Åtgärd mot trötthet"],
  ['tro-002', 'trotthet', 'trotthet', 2, 'reviewed', "Tecken på trötthet"],
  ['tro-003', 'trotthet', 'trotthet', 2, 'reviewed', "Trötthetens riskperioder"],
  ['tro-004', 'trotthet', 'stress-och-kanslor', 2, 'reviewed', "Stress i trafiken"],
  ['tro-005', 'trotthet', 'stress-och-kanslor', 2, 'reviewed', "Känslor och körning"],
  ['tro-006', 'trotthet', 'trotthet', 3, 'reviewed', "Trötthet jämfört med alkohol"],
  ['mor-001', 'morker', 'morkerkorning', 2, 'reviewed', "Hastighet i mörker"],
  ['mor-002', 'morker', 'ljusanvandning', 1, 'reviewed', "Halvljus"],
  ['mor-003', 'morker', 'mote-i-morker', 2, 'reviewed', "Bländning vid möte"],
  ['mor-004', 'morker', 'ljusanvandning', 2, 'reviewed', "Helljus"],
  ['mor-005', 'morker', 'morkerkorning', 2, 'reviewed', "Att upptäcka gående i mörker"],
  ['mor-006', 'morker', 'morkerkorning', 3, 'reviewed', "Avståndsbedömning i mörker"],
  ['mor-007', 'morker', 'ljusanvandning', 2, 'reviewed', "Dimljus"],
  ['mor-008', 'morker', 'mote-i-morker', 3, 'reviewed', "Mötet i mörker"],
  ['hal-001', 'halka', 'vattenplaning', 2, 'reviewed', "Åtgärd vid vattenplaning"],
  ['hal-002', 'halka', 'vattenplaning', 2, 'reviewed', "Risk för vattenplaning"],
  ['hal-003', 'halka', 'halka', 2, 'reviewed', "Bromssträcka vid halka"],
  ['hal-004', 'halka', 'halka', 3, 'reviewed', "Var halkan uppstår först"],
  ['hal-005', 'halka', 'vinterkorning', 1, 'reviewed', "Vinterdäcksperiod"],
  ['hal-006', 'halka', 'vinterkorning', 2, 'reviewed', "Körteknik på halt underlag"],
  ['hal-007', 'halka', 'halka', 2, 'reviewed', "Underkylt regn"],
  ['hal-008', 'halka', 'dimma', 2, 'reviewed', "Körning i dimma"],
  ['hal-009', 'halka', 'vinterkorning', 2, 'reviewed', "Sikt och snö på fordonet"],
  ['mil-001', 'miljo', 'sparsam-korning', 2, 'reviewed', "Sparsam körning"],
  ['mil-002', 'miljo', 'sparsam-korning', 2, 'reviewed', "Faktorer som påverkar förbrukningen"],
  ['mil-003', 'miljo', 'sparsam-korning', 2, 'reviewed', "Kallstart"],
  ['mil-004', 'miljo', 'miljopaverkan', 2, 'reviewed', "Avgasers påverkan"],
  ['mil-005', 'miljo', 'miljopaverkan', 2, 'reviewed', "Partiklar och dubbdäck"],
  ['mil-006', 'miljo', 'sparsam-korning', 3, 'reviewed', "Hastighet och förbrukning"],
  ['for-001', 'fordonet', 'dack-och-bromsar', 2, 'reviewed', "Mönsterdjup"],
  ['for-002', 'fordonet', 'dack-och-bromsar', 2, 'reviewed', "Lufttryck i däck"],
  ['for-003', 'fordonet', 'dack-och-bromsar', 2, 'reviewed', "ABS-bromsar"],
  ['for-004', 'fordonet', 'belysning-fordon', 1, 'reviewed', "Trasig lykta"],
  ['for-005', 'fordonet', 'kontroll-besiktning', 2, 'reviewed', "Körförbud"],
  ['for-006', 'fordonet', 'kontroll-besiktning', 2, 'reviewed', "Förarens ansvar"],
  ['for-007', 'fordonet', 'belysning-fordon', 2, 'reviewed', "Varningsblinkers"],
  ['for-008', 'fordonet', 'dack-och-bromsar', 3, 'reviewed', "Blandning av däcktyper"],
  ['for-009', 'fordonet', 'kontroll-besiktning', 2, 'reviewed', "Varningslampor"],
  ['las-001', 'last', 'slapvagn', 2, 'reviewed', "B-behörighet och släp"],
  ['las-002', 'last', 'slapvagn', 2, 'reviewed', "Obromsat släp"],
  ['las-003', 'last', 'lastning', 2, 'reviewed', "Lastsäkring"],
  ['las-004', 'last', 'lastning', 2, 'reviewed', "Utskjutande last"],
  ['las-005', 'last', 'slapvagn', 3, 'reviewed', "Släpvagnens köregenskaper"],
  ['las-006', 'last', 'lastning', 2, 'reviewed', "Passagerare och bälte"],
  ['man-001', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Stoppsträckans delar"],
  ['man-002', 'manniskan', 'reaktion-och-sinnen', 3, 'reviewed', "Reaktionssträcka i praktiken"],
  ['man-003', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Faktorer som förlänger reaktionstiden"],
  ['man-004', 'manniskan', 'reaktion-och-sinnen', 1, 'reviewed', "Mobiltelefon under körning"],
  ['man-005', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Synens roll"],
  ['man-006', 'manniskan', 'attityd-och-grupptryck', 2, 'reviewed', "Grupptryck"],
  ['man-007', 'manniskan', 'attityd-och-grupptryck', 3, 'reviewed', "Överskattning av egen förmåga"],
  ['man-008', 'manniskan', 'korstrategi', 2, 'reviewed', "Blickteknik"],
  ['man-009', 'manniskan', 'korstrategi', 3, 'reviewed', "Uppmärksamhetens gränser"],
  ['ned-001', 'manniskan', 'nedsatt-formaga', 2, 'reviewed', "Signaler med vit käpp"],
  ['ned-002', 'manniskan', 'nedsatt-formaga', 2, 'reviewed', "Att släppa över en synskadad"],
  ['ned-003', 'manniskan', 'nedsatt-formaga', 1, 'reviewed', "Ledarhund"],
  ['ned-004', 'manniskan', 'nedsatt-formaga', 3, 'reviewed', "Ålder och olycksrisk"],
  ['ned-005', 'manniskan', 'nedsatt-formaga', 2, 'reviewed', "Dolda funktionsnedsättningar"],
  ['ned-006', 'manniskan', 'nedsatt-formaga', 2, 'reviewed', "Tilläggstavla nedsatt syn"],
  ['ned-007', 'manniskan', 'nedsatt-formaga', 2, 'reviewed', "Särskild hänsyn mot barn"],
  ['rtp-001', 'trafikregler', 'rattspraxis', 3, 'reviewed', "Aktsamhetsplikten framför formell rätt"],
  ['rtp-002', 'trafikregler', 'rattspraxis', 3, 'reviewed', "Bevisning och eget ansvar"],
  ['krf-001', 'trafikregler', 'korfalt-och-sving', 2, 'reviewed', "Definitionen av körfält"],
  ['krf-002', 'hastighet', 'placering', 1, 'reviewed', "Placering i körfältet"],
  ['krf-003', 'hastighet', 'placering', 3, 'reviewed', "Placering vid god sikt framåt men skymd sikt åt sidorna"],
  ['krf-004', 'trafikregler', 'korfalt-och-sving', 2, 'reviewed', "Placering vid sväng"],
  ['krf-005', 'trafikregler', 'korfalt-och-sving', 3, 'reviewed', "Sväng på enkelriktad väg"],
  ['krf-006', 'hastighet', 'placering', 3, 'reviewed', "Val av körfält vid olika hastighetsgränser"],
  ['krf-007', 'hastighet', 'placering', 2, 'reviewed', "Fri körfältsplacering vid låg hastighet"],
  ['krf-008', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Kontroller före körfältsbyte"],
  ['krf-009', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Heldragen linje vid körfältsbyte"],
  ['krf-010', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Upprepade körfältsbyten i tät trafik"],
  ['krf-011', 'trafikregler', 'korfaltsbyte', 3, 'reviewed', "Hastighet vid körfältsbyte"],
  ['krf-012', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Kollektivkörfält"],
  ['krf-013', 'trafikregler', 'korfaltsbyte', 3, 'reviewed', "Reversibelt körfält"],
  ['krf-014', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Tecken vid körfältsbyte"],
  ['krk-001', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Deformationszoner"],
  ['krk-002', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Sidokollisionens särskilda risk"],
  ['krk-003', 'fordonet', 'krocksakerhet', 1, 'reviewed', "Ansvar för bältesanvändning"],
  ['krk-004', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Bältets placering"],
  ['krk-005', 'fordonet', 'krocksakerhet', 1, 'reviewed', "Krockkudde och bakåtvänd bilbarnstol"],
  ['krk-006', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Krockkudde och bälte"],
  ['krk-007', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Nackskydd och whiplash"],
  ['krk-008', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Barnskydd i bil"],
  ['fsl-001', 'fordonet', 'fordonsslag', 1, 'reviewed', "Begreppet trafikant"],
  ['fsl-002', 'fordonet', 'fordonsslag', 2, 'reviewed', "Högsta hastighet för lätt lastbil"],
  ['fsl-003', 'fordonet', 'fordonsslag', 2, 'reviewed', "Högsta hastighet med bromsad släpvagn"],
  ['fsl-004', 'fordonet', 'fordonsslag', 2, 'reviewed', "Högsta hastighet vid bogsering"],
  ['fsl-005', 'fordonet', 'fordonsslag', 2, 'reviewed', "Moped klass I och klass II"],
  ['fsl-006', 'fordonet', 'fordonsslag', 3, 'reviewed', "Varför andra fordons hastigheter spelar roll"],
  ['frs-001', 'fordonet', 'forsakring', 1, 'reviewed', "Trafikförsäkringens omfattning"],
  ['frs-002', 'fordonet', 'forsakring', 1, 'reviewed', "Krav på trafikförsäkring"],
  ['frs-003', 'fordonet', 'forsakring', 2, 'reviewed', "Halvförsäkring"],
  ['frs-004', 'fordonet', 'forsakring', 3, 'reviewed', "Regressrätt"],
  ['reg-001', 'fordonet', 'registrering', 2, 'reviewed', "Registreringsbevisets delar"],
  ['reg-002', 'fordonet', 'registrering', 3, 'reviewed', "Avställning sker aldrig automatiskt"],
  ['reg-003', 'fordonet', 'registrering', 2, 'reviewed', "Körning med avställt fordon"],
  ['reg-004', 'fordonet', 'registrering', 2, 'reviewed', "Försäkring vid ägarbyte"],
  ['drv-001', 'miljo', 'sparsam-korning', 2, 'reviewed', "Motorbromsning och bränsleförbrukning"],
  ['drv-002', 'miljo', 'sparsam-korning', 2, 'reviewed', "Växelval vid sparsam körning"],
  ['drv-003', 'miljo', 'sparsam-korning', 3, 'reviewed', "Acceleration vid sparsam körning"],
  ['drv-004', 'miljo', 'sparsam-korning', 2, 'reviewed', "Sparsam körning kontra trafiksäkerhet"],
  ['drv-005', 'miljo', 'sparsam-korning', 1, 'reviewed', "Takbox och luftmotstånd"],
  ['drv-006', 'miljo', 'sparsam-korning', 2, 'reviewed', "Däcktryck och förbrukning"],
  ['drv-007', 'miljo', 'sparsam-korning', 2, 'reviewed', "Motorvärmare"],
  ['drv-008', 'miljo', 'sparsam-korning', 1, 'reviewed', "Luftkonditionering och förbrukning"],
  ['drv-009', 'miljo', 'miljopaverkan', 2, 'reviewed', "Katalysatorns funktion"],
  ['drv-010', 'miljo', 'miljopaverkan', 2, 'reviewed', "Kolmonoxid"],
  ['drv-011', 'miljo', 'miljopaverkan', 1, 'reviewed', "Koldioxid och växthuseffekten"],
  ['drv-012', 'miljo', 'miljopaverkan', 2, 'reviewed', "Biltvätt"],
  ['drv-013', 'miljo', 'drivmedel', 2, 'reviewed', "Bensin jämfört med diesel"],
  ['drv-014', 'miljo', 'drivmedel', 1, 'reviewed', "Hybridbil"],
  ['drv-015', 'miljo', 'drivmedel', 3, 'reviewed', "Elbilens miljöpåverkan"],
  ['drv-016', 'miljo', 'drivmedel', 3, 'reviewed', "Miljözoner"],
  ['ber-002', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Reaktionssträcka vid längre reaktionstid"],
  ['ber-003', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Bromssträcka på torr asfalt"],
  ['ber-004', 'manniskan', 'reaktion-och-sinnen', 3, 'reviewed', "Stoppsträcka"],
  ['ber-008', 'hastighet', 'avstand', 3, 'reviewed', "Tresekundersregeln"],
  ['ber-009', 'manniskan', 'reaktion-och-sinnen', 3, 'reviewed', "Vad reaktionstiden beror på"],
  ['ber-010', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Vad som påverkar bromssträckan"],
  ['rtp-003', 'trafikregler', 'rattspraxis', 3, 'reviewed', "Hastighet som bedömningsgrund"],
  ['bld-001', 'hastighet', 'placering', 3, 'reviewed', "Körfältsval enligt körfältsvägvisare"],
  ['bld-002', 'korsningar', 'stopplikt', 2, 'reviewed', "Tilläggstavlan Flervägsstopp"],
  ['bld-003', 'korsningar', 'stopplikt', 2, 'reviewed', "Stopplikt i praktiken"],
  ['bld-004', 'korsningar', 'hogerregeln', 2, 'reviewed', "Att läsa av en korsning"],
  ['bld-005', 'korsningar', 'vajningsplikt', 2, 'reviewed', "Tunga fordon i korsning"],
  ['bld-006', 'trafikregler', 'oskyddade-trafikanter', 2, 'reviewed', "Obevakat övergångsställe"],
  ['bld-007', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Att skilja cykelöverfart från cykelpassage"],
  ['bld-008', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Bruten cykelbana"],
  ['bld-009', 'trafikregler', 'cykelpassage-overfart', 2, 'reviewed', "Övergångsställe kombinerat med cykelpassage"],
  ['bld-010', 'korsningar', 'cirkulationsplats', 2, 'reviewed', "Väjningsplikt vid infart"],
  ['bld-011', 'korsningar', 'cirkulationsplats', 3, 'reviewed', "Cirkelformad korsning som inte är cirkulationsplats"],
  ['bld-012', 'parkering', 'parkeringsregler', 3, 'reviewed', "Att läsa tilläggstavlor vid parkering"],
  ['bld-013', 'parkering', 'parkeringsregler', 3, 'reviewed', "Tider inom parentes på tilläggstavla"],
  ['bld-014', 'jarnvag', 'plankorsning-omkorning', 3, 'reviewed', "Omkörning vid plankorsning med bommar"],
  ['bld-015', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Gångfartsområde"],
  ['bld-016', 'omkorning', 'omkorningsregler', 3, 'reviewed', "Omkörningsbeslut på vinterväg"],
  ['vmk-001', 'vagmarken', 'varningsmarken', 1, 'reviewed', "Varningsmärkenas form och färg"],
  ['vmk-002', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Förbudsmärkenas form"],
  ['vmk-003', 'vagmarken', 'pabudsmarken', 1, 'reviewed', "Påbudsmärkenas innebörd"],
  ['vmk-004', 'vagmarken', 'varningsmarken', 1, 'reviewed', "Väjningsplikt (B1)"],
  ['vmk-005', 'vagmarken', 'varningsmarken', 1, 'reviewed', "Huvudled (B4)"],
  ['vmk-006', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Huvudled upphör (B5)"],
  ['vmk-007', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Stopplikt kontra väjningsplikt"],
  ['vmk-008', 'vagmarken', 'varningsmarken', 3, 'reviewed', "Flervägsstopp (T14)"],
  ['vmk-009', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Förbud mot att parkera (C35)"],
  ['vmk-010', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Förbud mot att stanna och parkera (C39)"],
  ['vmk-011', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Förbud mot infart (C1)"],
  ['vmk-012', 'vagmarken', 'forbudsmarken', 1, 'reviewed', "Hastighetsbegränsning (C31)"],
  ['vmk-013', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Rekommenderad lägre hastighet (E11)"],
  ['vmk-014', 'vagmarken', 'forbudsmarken', 2, 'reviewed', "Förbud mot omkörning (C27)"],
  ['vmk-015', 'vagmarken', 'forbudsmarken', 2, 'reviewed', "Slut på förbud mot omkörning (C28)"],
  ['vmk-016', 'vagmarken', 'pabudsmarken', 1, 'reviewed', "Cirkulationsplats (D3)"],
  ['vmk-017', 'vagmarken', 'pabudsmarken', 2, 'reviewed', "Påbjuden cykelbana (D4)"],
  ['vmk-018', 'vagmarken', 'pabudsmarken', 2, 'reviewed', "Kollektivkörfält (D10)"],
  ['vmk-019', 'vagmarken', 'anvisningsmarken', 1, 'reviewed', "Motorväg (E1)"],
  ['vmk-020', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Motorväg upphör (E2)"],
  ['vmk-023', 'vagmarken', 'anvisningsmarken', 3, 'reviewed', "Gågata kontra gångfartsområde"],
  ['vmk-024', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Tättbebyggt område (E5)"],
  ['vmk-025', 'vagmarken', 'anvisningsmarken', 1, 'reviewed', "Tidsangivelse på tilläggstavla (T6)"],
  ['vmk-026', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Parentestider på tilläggstavla"],
  ['vmk-027', 'vagmarken', 'anvisningsmarken', 3, 'reviewed', "Tilläggstavlan Boende (T19)"],
  ['vmk-028', 'vagmarken', 'anvisningsmarken', 3, 'reviewed', "Avstånd kontra utsträckning"],
  ['vmk-029', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Tilläggstavlan Riktning (T12)"],
  ['vmk-030', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Varning för vägkorsning (A28)"],
  ['vmk-031', 'vagmarken', 'varningsmarken', 1, 'reviewed', "Varning för barn (A15)"],
  ['vmk-032', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Varning för slirig väg (A10)"],
  ['vmk-033', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Järnvägskorsning med eller utan bommar"],
  ['vmk-034', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Heldragen linje"],
  ['vmk-035', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Stopplinje"],
  ['vmk-036', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Väjningslinje"],
  ['vmk-037', 'vagmarken', 'varningsmarken', 3, 'reviewed', "Rangordning av anvisningar"],
  ['vmk-038', 'vagmarken', 'varningsmarken', 3, 'reviewed', "Vägmärke före generell regel"],
  ['bl2-001', 'hastighet', 'hastighetsgranser', 2, 'reviewed', "Flera märken på samma stolpe"],
  ['bl2-002', 'motorvag', 'pafart-avfart', 2, 'reviewed', "Hastighet på avfart"],
  ['bl2-003', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Grön och blå vägvisning"],
  ['bl2-004', 'jarnvag', 'plankorsning-marken', 1, 'reviewed', "Kryssmärke vid plankorsning"],
  ['bl2-005', 'jarnvag', 'plankorsning-omkorning', 3, 'reviewed', "Bommar och omkörningsförbud"],
  ['bl2-006', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Gågata"],
  ['bl2-007', 'vagmarken', 'pabudsmarken', 1, 'reviewed', "Påbjuden körriktning"],
  ['bl2-008', 'vagmarken', 'anvisningsmarken', 2, 'reviewed', "Körfältsvägvisare"],
  ['bl2-009', 'motorvag', 'motorvag-regler', 2, 'reviewed', "Stillastående fordon på vägrenen"],
  ['bl2-010', 'motorvag', 'pafart-avfart', 3, 'reviewed', "Sammanvävning"],
  ['bl2-011', 'omkorning', 'omkorningsregler', 3, 'reviewed', "Sikt vid omkörning"],
  ['bl2-012', 'omkorning', 'omkorningsregler', 2, 'reviewed', "Omkörning på vinterväg"],
  ['bl2-013', 'motorvag', 'landsvag', 2, 'reviewed', "Vägkantens bärighet"],
  ['bl2-014', 'trafikregler', 'korfalt-och-sving', 2, 'reviewed', "Tillfälliga anvisningar vid vägarbete"],
  ['bl2-015', 'risker', 'skymd-sikt', 2, 'reviewed', "Stillastående buss"],
  ['bl2-016', 'motorvag', 'motorvag-regler', 1, 'reviewed', "Körfältsval på motorväg"],
  ['bl2-017', 'halka', 'vinterkorning', 1, 'reviewed', "Snötäckt vägbana"],
  ['bl2-018', 'motorvag', 'landsvag', 1, 'reviewed', "Kantlinjens betydelse"],
  ['bl3-001', 'risker', 'skymd-sikt', 2, 'reviewed', "Sidoavstånd till cyklist"],
  ['bl3-002', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Stannade bussar skymmer"],
  ['bl3-003', 'risker', 'skymd-sikt', 3, 'reviewed', "Enfilig passage med skymd utfart"],
  ['bl3-004', 'halka', 'vinterkorning', 2, 'reviewed', "Väglag i solsken"],
  ['bl3-005', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Huvudled och cykelpassage"],
  ['bl3-006', 'risker', 'skymd-sikt', 2, 'reviewed', "Luckor mellan parkerade fordon"],
  ['bl3-007', 'trafikregler', 'vagens-anvandning', 3, 'reviewed', "Kryssmärke vid spårväg"],
  ['bl3-008', 'korsningar', 'polisens-tecken', 2, 'reviewed', "Signal före vägmärke"],
  ['bl4-001', 'last', 'lastning', 3, 'reviewed', "Last som skjuter ut i sidled"],
  ['bl4-002', 'last', 'slapvagn', 3, 'reviewed', "Lastens placering i släpet"],
  ['bl4-003', 'morker', 'mote-i-morker', 2, 'reviewed', "När helljuset ska tillbaka"],
  ['bl4-004', 'morker', 'mote-i-morker', 3, 'reviewed', "Avbländning i kurva"],
  ['bl4-005', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Passagerarkrockkudde och bakåtvänd stol"],
  ['bl4-006', 'last', 'slapvagn', 2, 'reviewed', "Utmärkning av bogserlina"],
  ['egr-001', 'fordonet', 'dack-och-bromsar', 2, 'reviewed', "Slitagemönster som tecken på lufttryck"],
  ['egr-002', 'fordonet', 'dack-och-bromsar', 2, 'reviewed', "Blåsa på däcksidan"],
  ['egr-003', 'halka', 'vattenplaning', 2, 'reviewed', "Att hantera vattenplaning"],
  ['egr-004', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Nackskyddets höjd"],
  ['egr-005', 'fordonet', 'krocksakerhet', 2, 'reviewed', "Bältets placering över kroppen"],
  ['skk-001', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Avståndstavla under varningsmärke"],
  ['skk-002', 'parkering', 'parkeringsforbud', 2, 'reviewed', "Utsträckningstavla under förbudsmärke"],
  ['skk-003', 'parkering', 'parkeringsregler', 3, 'reviewed', "Parkering med tid och avgift"],
  ['skk-004', 'korsningar', 'vajningsplikt', 3, 'reviewed', "Flervägsväjning"],
  ['skk-005', 'korsningar', 'stopplikt', 2, 'reviewed', "Förvarning om stopplikt"],
  ['skk-006', 'parkering', 'parkeringsregler', 2, 'reviewed', "Tavla för rörelsehindrade"],
  ['skk-007', 'korsningar', 'huvudled', 3, 'reviewed', "Vägars fortsättning i korsning"],
  ['skk-008', 'omkorning', 'omkorningsforbud', 2, 'reviewed', "Sträckans längd under omkörningsförbud"],
  ['skk-009', 'vagmarken', 'forbudsmarken', 3, 'reviewed', "Viktbegränsning genom tilläggstavla"],
  ['skk-010', 'parkering', 'stannande-forbud', 3, 'reviewed', "Riktningstavla under förbudsmärke"],
  ['skk-011', 'korsningar', 'stopplikt', 2, 'reviewed', "Flervägsstopp"],
  ['skk-012', 'vagmarken', 'varningsmarken', 2, 'reviewed', "Märke utan tilläggstavla"],
  ['grd-001', 'korsningar', 'hogerregeln', 1, 'reviewed', "Högerregeln"],
  ['grd-002', 'trafikregler', 'trafiksignaler', 1, 'reviewed', "Gult ljus"],
  ['grd-003', 'hastighet', 'hastighetsgranser', 1, 'reviewed', "Bashastighet utanför tätort"],
  ['grd-004', 'trafikregler', 'grundregler', 1, 'reviewed', "Bältesanvändning"],
  ['grd-005', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Mittlinje och kantlinje"],
  ['grd-006', 'alkohol', 'alkohol-gransvarden', 1, 'reviewed', "Grovt rattfylleri"],
  ['grd-007', 'morker', 'ljusanvandning', 1, 'reviewed', "Halvljus"],
  ['grd-008', 'trafikregler', 'vagens-anvandning', 1, 'reviewed', "Fri väg för utryckningsfordon"],
  ['grd-009', 'trafikregler', 'grundregler', 1, 'reviewed', "Aktsamhetsplikten"],
  ['grd-010', 'fordonet', 'dack-och-bromsar', 1, 'reviewed', "Mönsterdjup på sommardäck"],
  ['grd-011', 'trafikregler', 'oskyddade-trafikanter', 1, 'reviewed', "Väjningsplikt vid obevakat övergångsställe"],
  ['grd-012', 'motorvag', 'motorvag-regler', 1, 'reviewed', "Förbjudet på motorväg"],
  ['grd-013', 'vagmarken', 'anvisningsmarken', 1, 'reviewed', "Parkeringsmärket"],
  ['grd-014', 'trotthet', 'trotthet', 1, 'reviewed', "Åtgärd mot trötthet"],
  ['mns-001', 'manniskan', 'korstrategi', 2, 'reviewed', "Överinlärning"],
  ['mns-002', 'manniskan', 'korstrategi', 2, 'reviewed', "Ytinlärning"],
  ['mns-003', 'manniskan', 'korstrategi', 3, 'reviewed', "Sannolikhetsinlärning"],
  ['mns-004', 'manniskan', 'korstrategi', 2, 'reviewed', "Imitationsinlärning"],
  ['mns-005', 'manniskan', 'attityd-och-grupptryck', 2, 'reviewed', "Mognadsgrader hos förare"],
  ['mns-006', 'manniskan', 'attityd-och-grupptryck', 3, 'reviewed', "Unga förares riskökning"],
  ['mns-007', 'manniskan', 'attityd-och-grupptryck', 2, 'reviewed', "Negativt grupptryck"],
  ['mns-008', 'manniskan', 'attityd-och-grupptryck', 2, 'reviewed', "Positivt grupptryck"],
  ['mns-009', 'manniskan', 'korstrategi', 3, 'reviewed', "Att frångå reglerna med gott omdöme"],
  ['mns-010', 'trotthet', 'stress-och-kanslor', 3, 'reviewed', "Stressnivå och prestation"],
  ['mns-011', 'trotthet', 'stress-och-kanslor', 2, 'reviewed', "Följder av hög stress"],
  ['mns-012', 'trotthet', 'stress-och-kanslor', 1, 'reviewed', "Att minska stress"],
  ['mns-013', 'trotthet', 'stress-och-kanslor', 3, 'reviewed', "Känslor och körning"],
  ['mns-014', 'alkohol', 'alkohol-effekter', 2, 'reviewed', "Effekt vid låg promillehalt"],
  ['mns-015', 'alkohol', 'alkohol-effekter', 3, 'reviewed', "Individuell variation i promillehalt"],
  ['mns-016', 'alkohol', 'alkohol-effekter', 2, 'reviewed', "Dagen efter"],
  ['mns-017', 'alkohol', 'alkohol-gransvarden', 3, 'reviewed', "Rattfylleri under gränsvärdet"],
  ['mns-018', 'alkohol', 'alkohol-gransvarden', 2, 'reviewed', "Medhjälp till rattfylleri"],
  ['mns-019', 'alkohol', 'alkohol-gransvarden', 2, 'reviewed', "Var rattfyllerilagen gäller"],
  ['mns-020', 'alkohol', 'droger-lakemedel', 2, 'reviewed', "Ansvar för läkemedelspåverkan"],
  ['mns-021', 'alkohol', 'droger-lakemedel', 2, 'reviewed', "Nolltolerans mot narkotika"],
  ['mns-022', 'alkohol', 'droger-lakemedel', 3, 'reviewed', "Vakenhetshöjande droger"],
  ['mns-023', 'alkohol', 'droger-lakemedel', 3, 'reviewed', "Alkohol kombinerat med läkemedel"],
  ['mns-024', 'trotthet', 'trotthet', 3, 'reviewed', "Sömnbrist jämfört med alkohol"],
  ['mns-025', 'trotthet', 'trotthet', 2, 'reviewed', "Monotoni som trötthetsorsak"],
  ['mns-026', 'trotthet', 'trotthet', 2, 'reviewed', "Trötthetssignaler"],
  ['mns-027', 'trotthet', 'trotthet', 2, 'reviewed', "Mikrosömn"],
  ['mns-028', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Barns sinnen"],
  ['mns-029', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Barns riskbedömning"],
  ['mns-030', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Barn bakom parkerade fordon"],
  ['mns-031', 'risker', 'barn-och-oskyddade', 3, 'reviewed', "Ögonkontakt med barn"],
  ['mns-032', 'risker', 'barn-och-oskyddade', 2, 'reviewed', "Barn vid bussar"],
  ['mns-033', 'risker', 'djur-pa-vagen', 2, 'reviewed', "När viltrisken är störst"],
  ['mns-034', 'risker', 'djur-pa-vagen', 3, 'reviewed', "Undanmanöver vid älg"],
  ['mns-035', 'risker', 'djur-pa-vagen', 2, 'reviewed', "Efter en viltolycka"],
  ['mns-036', 'risker', 'riskbedomning', 3, 'reviewed', "Riskkompensation"],
  ['mns-037', 'risker', 'riskbedomning', 3, 'reviewed', "Tillbud som felaktig bekräftelse"],
  ['mns-038', 'risker', 'riskbedomning', 2, 'reviewed', "Rutin och uppmärksamhet"],
  ['mns-039', 'manniskan', 'reaktion-och-sinnen', 2, 'reviewed', "Mobiltelefon och uppmärksamhet"],
  ['mns-040', 'manniskan', 'reaktion-och-sinnen', 3, 'reviewed', "Blicktid och sträcka"],
  ['mrk-001', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Mittlinje (M1)"],
  ['mrk-002', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Varningslinje (M3)"],
  ['mrk-003', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Mittlinje kontra varningslinje"],
  ['mrk-004', 'vagmarken', 'vagmarkeringar', 3, 'reviewed', "Kombinerad linje (M10)"],
  ['mrk-005', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Kantlinje (M2)"],
  ['mrk-006', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Spärrområde (M9)"],
  ['mrk-007', 'vagmarken', 'vagmarkeringar', 1, 'reviewed', "Stopplinje (M13)"],
  ['mrk-008', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Väjningslinje (M14)"],
  ['mrk-009', 'trafikregler', 'cykelpassage-overfart', 3, 'reviewed', "Rutmarkering utan vägmärke"],
  ['mrk-010', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Övergångsställe kontra cykelpassage"],
  ['mrk-011', 'trafikregler', 'korfalt-och-sving', 2, 'reviewed', "Körfältspilar (M19)"],
  ['mrk-012', 'trafikregler', 'korfaltsbyte', 2, 'reviewed', "Bussymbol i körfältet (M28)"],
  ['mrk-013', 'vagmarken', 'vagmarkeringar', 3, 'reviewed', "Markering kontra vägmärke"],
  ['mrk-014', 'vagmarken', 'vagmarkeringar', 2, 'reviewed', "Ledlinje (M4)"],
];

export const QUESTION_INDEX: readonly QuestionIndexEntry[] = ROWS.map((r) => ({
  id: r[0],
  category: r[1] as CategoryId,
  subcategory: r[2],
  difficulty: r[3] as Difficulty,
  status: r[4] as QuestionStatus,
  ruleTested: r[5],
}));

export const QUESTION_INDEX_BY_ID: ReadonlyMap<string, QuestionIndexEntry> = new Map(
  QUESTION_INDEX.map((q) => [q.id, q]),
);

/** Learner-visible questions only — draft, rejected and retired stay out. */
export const ACTIVE_QUESTION_INDEX: readonly QuestionIndexEntry[] =
  QUESTION_INDEX.filter((q) => LEARNER_VISIBLE_STATUSES.includes(q.status));

/** Bank statistics, so the landing page needs no question bodies. */
export const BANK_TOTALS = {
  total: 454,
  easy: 84,
  medium: 255,
  hard: 115,
} as const;
